config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }

  get  '/v1.0',                     to: 'users#index'
  get  '/v1.0/user/devices',        to: 'users#devices'
  post '/v1.0/user/unlink',         to: 'users#unlink'
  post '/v1.0/user/devices/query',  to: 'users#query'
  post '/v1.0/user/devices/action', to: 'users#action'

  resources :users
  resources :devices do
    resources :capabilities
  end

  root 'devices#index'
end

app/models/device.rb
# frozen_string_literal: true

class Device < ApplicationRecord
  has_many :capabilities, inverse_of: :device
  accepts_nested_attributes_for :capabilities, reject_if: :all_blank, allow_destroy: true
  belongs_to :user

  TYPES = [
    ['devices.types.light',                 'Лампочка, светильник, люстра.'],
    ['devices.types.socket',                'Розетка.'],
    ['devices.types.switch',                'Выключатель, реле.'],
    ['devices.types.thermostat',            'Водонагреватель, теплый пол, обогреватель, электровентилятор.'],
    ['devices.types.thermostat.ac',         'Кондиционер.'],
    ['devices.types.media_device',          'Аудио, видео, мультимедиа техника.'],
    ['devices.types.media_device.tv',       'Телевизор, ИК-пульт от телевизора'],
    ['devices.types.media_device.tv_box',   'ИК-пульт от тв-приставки, тв-приставка.'],
    ['devices.types.media_device.receiver', 'ИК-пульт от ресивера, ресивер.'],
    ['devices.types.cooking',               'Различная умная кухонная техника.'],
    ['devices.types.cooking.coffee_maker',  'Кофеварка, кофемашина.'],
    ['devices.types.cooking.kettle',        'Чайник.'],
    ['devices.types.cooking.multicooker',   'Мультиварка.'],
    ['devices.types.openable',              'Дверь, ворота, окно, ставни.'],
    ['devices.types.openable.curtain',      'Шторы, жалюзи.'],
    ['devices.types.humidifier',            'Увлажнитель воздуха.'],
    ['devices.types.purifier',              'Очиститель воздуха.'],
    ['devices.types.vacuum_cleaner',        'Робот-пылесос.'],
    ['devices.types.washing_machine',       'Стиральная машина.'],
    ['devices.types.dishwasher',            'Посудомоечная машина.'],
    ['devices.types.iron',                  'Утюг, парогенератор.'],
    ['devices.types.sensor',                'Датчик температуры, влажности, открытия двери, движения.'],
    ['devices.types.other',                 'Остальные устройства.']
  ].freeze

  PINS = [
    { id:  1, bg: 'warning',   num: nil, comment: '3v3'       }, { id:  2, bg: 'danger',    num: nil, comment: '5v0'       },
    { id:  3, bg: 'primary',   num: 2,   comment: 'SDA'       }, { id:  4, bg: 'danger',    num: nil, comment: '5v0'       },
    { id:  5, bg: 'primary',   num: 3,   comment: 'SCL'       }, { id:  6, bg: 'secondary', num: nil, comment: 'GND'       },
    { id:  7, bg: 'success',   num: 4,   comment: 'GPCLK0'    }, { id:  8, bg: 'light',     num: 14,  comment: 'TXD'       },
    { id:  9, bg: 'secondary', num: nil, comment: 'GND'       }, { id: 10, bg: 'light',     num: 15,  comment: 'RXD'       },
    { id: 11, bg: 'success',   num: 17,  comment: 'SPI CE1'   }, { id: 12, bg: 'success',   num: 18,  comment: 'SPI CE0'   },
    { id: 13, bg: 'success',   num: 27,  comment: '-'         }, { id: 14, bg: 'secondary', num: nil, comment: 'GND'       },
    { id: 15, bg: 'success',   num: 22,  comment: '-'         }, { id: 16, bg: 'success',   num: 23,  comment: '-'         },
    { id: 17, bg: 'warning',   num: nil, comment: '3v3'       }, { id: 18, bg: 'success',   num: 24,  comment: '-'         },
    { id: 19, bg: 'info',      num: 10,  comment: 'SPI0 MOS'  }, { id: 20, bg: 'secondary', num: nil, comment: 'GND'       },
    { id: 21, bg: 'info',      num: 9,   comment: 'SPI0 MISO' }, { id: 22, bg: 'success',   num: 25,  comment: '-'         },
    { id: 23, bg: 'info',      num: 11,  comment: 'SPI0 SCLK' }, { id: 24, bg: 'info',      num: 8,   comment: 'SPI0 CE0'  },
    { id: 25, bg: 'secondary', num: nil, comment: 'GND'       }, { id: 26, bg: 'info',      num: 7,   comment: 'SPI0 CE1'  },
    { id: 27, bg: 'primary',   num: 0,   comment: 'ID_SD'     }, { id: 28, bg: 'primary',   num: 1,   comment: '-'         },
    { id: 29, bg: 'success',   num: 5,   comment: '-'         }, { id: 30, bg: 'secondary', num: nil, comment: 'GND'       },
    { id: 31, bg: 'success',   num: 6,   comment: '-'         }, { id: 32, bg: 'success',   num: 12,  comment: 'PWM0'      },
    { id: 33, bg: 'success',   num: 13,  comment: 'PWM1'      }, { id: 34, bg: 'secondary', num: nil, comment: 'GND'       },
    { id: 35, bg: 'info',      num: nil, comment: 'SPI1 MISO' }, { id: 36, bg: 'success',   num: 16,  comment: 'SPI1 CE2'  },
    { id: 37, bg: 'success',   num: 26,  comment: '-'         }, { id: 38, bg: 'info',      num: 20,  comment: 'SPI1 MOSI' },
    { id: 39, bg: 'secondary', num: nil, comment: 'GND'       }, { id: 40, bg: 'info',      num: 21,  comment: 'SPI1 SCLK' }
  ].freeze

  INFO = {
    mac: `ifconfig`.split('ether ')[1][0..16],
    name: 'Bosch_BME280',
    owner: 'dvitvitskiy.pro@gmail.com'
  }.freeze

  def self.narod_mon
    bme280 = JSON.parse RestClient.get('krsz.ru:3004/bme280')
    data = [
      { id: 't', name: 'Температура', value: bme280['t'], unit: 'C'   },
      { id: 'p', name: 'Давление',    value: bme280['p'], unit: 'HPA' },
      { id: 'h', name: 'Влажность',   value: bme280['h'], unit: 'HUM' }
    ]
    RestClient.post('http://narodmon.ru/post', { devices: [INFO.merge(sensors: data)] }.to_json)
  end

  def self.user_devices(user_id)
    eager_load(:capabilities).where(user_id: user_id).map do |d|
      {
        id: d.id.to_s,
        name: d.name,
        description: d.description,
        room: d.room,
        type: d.device_type,
        custom_data: {},
        device_info: { manufacturer: d.manufacturer, model: d.model, hw_version: d.hw_version, sw_version: d.sw_version },
        capabilities: d.capabilities.map { |cap| { type: cap.capability_type, retrievable: cap.retrievable } }
      }
    end
  end

  def self.user_query(user_id)
    eager_load(:capabilities).where(user_id: user_id).map do |d|
      {
        id: d.id, capabilities: d.capabilities.map do |cap|
          { type: cap.capability_type, state: { instance: cap.state_instance, value: true } }
        end
      }
    end
  end
end

app/controllers/devices_controller.rb
# frozen_string_literal: true

class DevicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  def index
    # @mhz19b = JSON.parse RestClient.get('krsz.ru:3004/mhz19b')
    # @bme280 = JSON.parse RestClient.get('krsz.ru:3004/bme280')
    # @gpio   = JSON.parse RestClient.get('krsz.ru:3004/pins')
    @devices = current_user.devices.eager_load(:capabilities)
  end

  def show
    render :edit
  end

  def new
    @device = current_user.devices.new
  end

  def edit; end

  def create
    @device = current_user.devices.new(device_params)

    if @device.save
      redirect_to devices_path, notice: 'Устройство создано!'
    else
      render :new
    end
  end

  def update
    if @device.update(device_params)
      redirect_to devices_path, notice: 'Устройство обновлено!'
    else
      render :edit
    end
  end

  def destroy
    @device.destroy
    redirect_to devices_url, notice: 'Устройство удалено!'
  end

  private

  def set_device
    @device = current_user.devices.find(params[:id])
  end

  def device_params
    params.require(:device)
          .permit(:enabled, :name, :description, :room, :device_type, :manufacturer, :model, :hw_version, :sw_version, :host, :port,
                  capabilities_attributes: %i[id enabled retrievable capability_type state state_instance state_value path pin status _destroy])
  end
end

app/views/devices/_capability_fields.slim
.card.text-white.bg-dark.mb-3
  .nested-fields
    .card-body
      .card-link
        = link_to_remove_association "Удалить", f
      .field
        .row
          .col-sm-4
            .form-group.row
              = f.label :enabled, 'Активирован?', class: 'col-form-label'
              = f.check_box :enabled, class: 'form-control'
          .col-sm-4
            .form-group.row
              = f.label :retrievable, 'retrievable', class: 'col-form-label'
              = f.check_box :retrievable, class: 'form-control'
          .col-sm-4
            .form-group.row
              = f.label :status, 'status', class: 'col-form-label'
              = f.check_box :status, class: 'form-control'
        .form-group.row
          = f.label :capability_type, 'capability_type', class: 'col-sm-4 col-form-label'
          .col-sm-8
            = f.text_field :capability_type, class: 'form-control'
        .form-group.row
          = f.label :state_instance, 'state_instance', class: 'col-sm-4 col-form-label'
          .col-sm-8
            = f.text_field :state_instance, class: 'form-control'
        .form-group.row
          = f.label :state_value, 'state_value', class: 'col-sm-4 col-form-label'
          .col-sm-8
            = f.number_field :state_value, class: 'form-control'
        .form-group.row
          = f.label :state, 'state', class: 'col-sm-4 col-form-label'
          .col-sm-8
            = f.select :state, Capability::TYPES, {}, class: 'form-control'
        .form-group.row
          = f.label :path, 'path', class: 'col-sm-4 col-form-label'
          .col-sm-8
            = f.text_field :path, class: 'form-control'
        .form-group.row
          = f.label :pin, 'pin', class: 'col-sm-4 col-form-label'
          .col-sm-8
            = f.number_field :pin, class: 'form-control'
        = f.hidden_field :id
br

app/views/devices/_form.slim
= form_with model: @device, remote: false do |f|
  .row
    .col-12
      .actions.row
        .col-sm-4
          = link_to 'Назад', devices_path, class: 'btn btn-secondary btn-block'
        .col-sm-4
          - if @device.id
            = link_to 'Удалить', @device, data: {confirm: 'Вы уверены?'}, method: :delete, class: 'btn btn-danger btn-block'
        .col-sm-4
          = f.submit 'Сохранить', class: 'btn btn-success btn-block'
  .row
    .col-12
      p
  .row
    .col-6
      .card.text-white.bg-dark.mb-3
        .card-body
        p
        - if @device.errors.any?
          #error_explanation
            h2 = "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
            ul
              - @device.errors.full_messages.each do |message|
                li = message
        .form-group.row
          = f.label :enabled, 'Активирован?', class: 'col-sm-4 col-form-label text-white-50'
          .col-sm-8
            = f.check_box :enabled, class: 'form-control'
        .form-group.row
          = f.label :name, 'Наименование', class: 'col-sm-4 col-form-label text-white-50'
          .col-sm-8
            = f.text_field :name, class: 'form-control'
        .form-group.row
          = f.label :description, 'Описание', class: 'col-sm-4 col-form-label text-white-50'
          .col-sm-8
            = f.text_field :description, class: 'form-control'
        .form-group.row
          = f.label :room, 'Помещение', class: 'col-sm-4 col-form-label text-white-50'
          .col-sm-8
            = f.text_field :room, class: 'form-control'
        .form-group.row
          = f.label :device_type, 'Тип', class: 'col-sm-4 col-form-label text-white-50'
          .col-sm-8
            = f.select :device_type, Device::TYPES, {}, class: 'form-control'
        .form-group.row
          = f.label :manufacturer, 'Производитель', class: 'col-sm-4 col-form-label text-white-50'
          .col-sm-8
            = f.text_field :manufacturer, class: 'form-control'
        .form-group.row
          = f.label :model, 'Модель', class: 'col-sm-4 col-form-label text-white-50'
          .col-sm-8
            = f.text_field :model, class: 'form-control'
        .form-group.row
          = f.label :hw_version, 'Версия железа', class: 'col-sm-4 col-form-label text-white-50'
          .col-sm-8
            = f.text_field :hw_version, class: 'form-control'
        .form-group.row
          = f.label :sw_version, 'Версия софта', class: 'col-sm-4 col-form-label text-white-50'
          .col-sm-8
            = f.text_field :sw_version, class: 'form-control'
      p
      .card.bg-dark.mb-3
        .card-body
          .col-12
            - Device::PINS.each_slice(2) do |left, right|
              .row
                .col-3.text-right class="bg-#{left[:bg]}"
                  = left[:comment]
                .col-2.text-white-50
                  = left[:num]
                .col-1.text-white-50 class="#{left[:bg] == 'success' ? "bg-#{left[:bg]}" : ''}"
                  = check_box_tag "gpio_pins[]", true, left[:num].nil?, disabled: left[:bg] != 'success'
                .col-1.text-white-50 class="#{right[:bg] == 'success' ? "bg-#{right[:bg]}" : ''}"
                  = check_box_tag "gpio_pins[]", true, right[:num].nil?, disabled: right[:bg] != 'success'
                .col-2.text-white-50
                  = right[:num]
                .col-3.text-left class="bg-#{right[:bg]}"
                  = right[:comment]
    .col-6
      #capabilities
        = f.fields_for :capabilities do |capability|
          = render 'capability_fields', f: capability
        .links
          = link_to_add_association 'Добавить навык', f, :capabilities, class: 'btn btn-primary'
      br
  .row
    .col-12
      .actions.row
        .col-sm-4
          = link_to 'Назад', devices_path, class: 'btn btn-secondary btn-block'
        .col-sm-4
          - if @device.id
            = link_to 'Удалить', @device, data: {confirm: 'Вы уверены?'}, method: :delete, class: 'btn btn-danger btn-block'
        .col-sm-4
          = f.submit 'Сохранить', class: 'btn btn-success btn-block'

app/views/devices/edit.slim
section#devices_edit_section.signup-section.bg-black.text-center
  .container
    .row
      .col-2
      .col-8
        h3.text-white-50 Устройство "#{@device.name}" в помещении "#{@device.room}"
      .col-2
    .row
      .col-12
        == render 'form'

app/views/devices/index.slim
section#devices_list_section.signup-section.bg-black.text-center
  .container
    .notice = notice
    .alert = alert
    .row
      .col-2
      .col-8
        h1.text-white-50 Список устройств
      .col-2
        = link_to 'Добавить', new_device_path, class: 'btn btn-xs btn-success'
    br
    .row
      .col-12
        table.table.table-dark
          thead
            tr
              td Наименование
              td Подключен?
              td Местоположение
              td Тип навыка
              td Хост
              td Порт
          tbody
            - @devices.each do |device|
              tr.text-white-50 data-link="#{edit_device_path(device)}"
                td= device.name
                td= device.enabled
                td= device.room
                td= device.device_type
                td= device.host
                td= device.port

javascript:
    $("tr[data-link]").click( function() { window.location = $(this).data("link") } )

app/views/devices/new.slim
section#devices_new_section.signup-section.bg-black.text-center
  .container
    .row
      .col-2
      .col-8
        h1.text-white-50 Новое устройство
      .col-2
    .row
      .col-12
        == render 'form'

app/views/devices/show.slim
section#devices_show_section.signup-section.bg-black.text-center
  .container
    .row
      .col-6
        = form_tag device_path(@device), method: :put do
          - Device::PINS.each_slice(2) do |left, right|
            .row
              .col-4.text-right class="bg-#{left[:bg]}"
                = left[:comment]
              .col-1.text-white-50
                = left[:num]
              .col-1.text-white-50 class="#{left[:bg] == 'success' ? "bg-#{left[:bg]}" : ''}"
                = check_box_tag "gpio_pins[]", true, left[:num].nil?, disabled: left[:bg] != 'success'
              .col-1.text-white-50 class="#{right[:bg] == 'success' ? "bg-#{right[:bg]}" : ''}"
                = check_box_tag "gpio_pins[]", true, right[:num].nil?, disabled: right[:bg] != 'success'
              .col-1.text-white-50
                = right[:num]
              .col-4.text-left class="bg-#{right[:bg]}"
                = right[:comment]
        / = submit_tag 'SET GPIO', class: 'btn btn-xs btn-success'
      .col-6
        div
          - if @bme280.present?
            div.text-left.text-white-50 Температура: #{@bme280['t']}
            div.text-left.text-white-50 Давление: #{@bme280['p']}
            div.text-left.text-white-50 Влажность: #{@bme280['h']}
        div
          - if @sens.present? && @sens['crc']
            p Температура: #{@sens['temp']}
            p CO2: #{@sens['co2']}

    = link_to 'Edit', edit_device_path(@device)
    = link_to 'Back', devices_path
    = link_to 'Destroy', @device, data: {confirm: 'Are you sure?'}, method: :delete